// <auto-generated />
using EventSourcingPoc.API.EFContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventSourcingPoc.API.EFContext.Migrations
{
    [DbContext(typeof(GuaranteeContext))]
    [Migration("20260623164300_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventSourcingPoc.API.EFContext.Bond", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_bonds");

                    b.ToTable("bonds", (string)null);
                });

            modelBuilder.Entity("EventSourcingPoc.API.EFContext.Insurance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("EnterpriseFactor")
                        .HasColumnType("numeric")
                        .HasColumnName("enterprise_factor");

                    b.Property<decimal>("ExecutiveFactor")
                        .HasColumnType("numeric")
                        .HasColumnName("executive_factor");

                    b.Property<decimal>("ExecutiveRenewalFactor")
                        .HasColumnType("numeric")
                        .HasColumnName("executive_renewal_factor");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_insurances");

                    b.ToTable("insurances", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
