// <auto-generated />
using System;
using EventSourcingPoc.API.Projections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventSourcingPoc.API.Migrations.ProjectionsDb
{
    [DbContext(typeof(ProjectionContext))]
    partial class ProjectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventSourcingPoc.API.Projections.CustomerSummary", b =>
                {
                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UsedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TaxId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.ToTable("CustomerSummaries");
                });

            modelBuilder.Entity("EventSourcingPoc.API.Projections.ProjectionCheckpoint", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastProcessedSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectionName");

                    b.ToTable("ProjectionCheckpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
